### ISSUE TITLE
Create Statement v1

### ISSUE THREAD

**Issue by TomHennen** [in-toto/attestation#130]
SLSA is working on publishing SLSA 1.0.  Since the SLSA provenance spec uses in-toto statements it might be nice if they had a v1 of statements to use in their provenance spec.

The statement definition has been pretty stable.  Should we rev it to v1?

The one change that we might consider is adding an 'attestor id' field to the statement layer.  Rationale: [SLSA provenance](https://slsa.dev/provenance/v0.2#builder.id), [VSAs](https://slsa.dev/verification_summary/v0.2#verifier.id), [proposed runtime trace](https://github.com/in-toto/attestation/pull/111/files#diff-c1a4f7ac32ae7837cb9a3fb9e656a84d214432d3913a78453b21adb8fce526d9R81) [proposed reference attestations](https://github.com/in-toto/attestation/issues/117#issuecomment-1333815831) all have some sort of ID in the predicate field.  It might be helpful to up-level this to the statement so it can be standardized.  If folks don't like this idea we can drop it.

[EDIT] Blockers:
- [X] Get resolution on #133 @marcelamelara 
~~- [ ] Decide adding an 'attestor id' field to the statement layer (per above).~~
- [x] Resolve #135
- [x] Clarify DigestSet terminology [per this comment](https://github.com/in-toto/attestation/issues/130#issuecomment-1416022258) and [this comment](https://github.com/in-toto/attestation/pull/135#discussion_r1114675451) (probably blocked on #133?) @TomHennen 
- [x] Address #127 @joshuagl 
- [x] Resolve #131 
- [x] Determine inclusion (and resolution?) of #137 
- [x] Remove .0 from version number per [this comment](https://github.com/in-toto/attestation/issues/130#issuecomment-1435317334) @pxp928 
- [x] Resolve #143 @marcelamelara 
- [x] Remove "-draft" from all files
- [x] Resolve #157 @TomHennen & @pxp928

**Comment by MarkLodato** [comment]
Another topic that has come up is the encoding of digests, e.g. #108. Currently the spec says:

> Set of alternative cryptographic digests [...] expressed as a JSON map from algorithm name to **lowercase hex-encoded value**.

There is some desire to either:

- Allow alternative encodings, such as base64 for `goModuleH1` since base64 is more natural for go (it's what other systems use).
- Switch them all to base64.
  - Advantages:
    - Smaller encoding
    - More natural in proto to say that it's a `bytes` field, which is unambiguous - always store the raw binary value (encoded in JSON as base64), rather than storing a hex value that may be uppercase or lowercase.
  - Disadvantages:
    - Less natural for systems that represent digests in hex, such as container images

**Comment by TomHennen** [comment]
We have internal cases that have special characters (e.g. '-') so I'd probably prefer to leave it as a string regardless of the other outcomes.  Maybe that would still be OK and just somewhat more awkward?

My weak preference is to allow lowercase hex or lowercase base64 for the 'standard' values to ease migration.

**Comment by TomHennen** [comment]
@marcelamelara suggests that we might also consider making the subject field contain reference 'types' (in a backwards compatible way) see #117.

**Comment by marcelamelara** [comment]
I'm fine with supporting both hex and base64 encoded digests, and can update the documentation to state this explicitly. I also think that the question of digest encoding can (somewhat) be addressed by making the subject field a Reference (per #133), which is very much akin to the ArtifactReference in SLSA Provenance v1.0.

**Comment by TomHennen** [comment]
Current known blockers:

1. Get resolution on #133, #135
2. Clarify DigestSet terminology [per this comment](https://github.com/in-toto/attestation/issues/130#issuecomment-1416022258) (probably blocked on #133?)

**Comment by marcelamelara** [comment]
Additional blockers:
- [ ] Resolve #127 
- [ ] MVP for #131

**Comment by marcelamelara** [comment]
Just added a checklist for the blockers above, per our discussions. Feel free to edit.

**Comment by TomHennen** [comment]
For "Decide adding an 'attestor id' field to the statement layer (per above)." I suggest we drop it.  The current model generally works fine and prevents ambiguity.

**Comment by MarkLodato** [comment]
Any thoughts on including #136 in v1? Now seems like a good time to decide that.

**Comment by TomHennen** [comment]
> Any thoughts on including #136 in v1? Now seems like a good time to decide that.

That would be fine with me.  Pretty easy change.

**Comment by MarkLodato** [comment]
> For "Decide adding an 'attestor id' field to the statement layer (per above)." I suggest we drop it. The current model generally works fine and prevents ambiguity.

This came up again in https://github.com/slsa-framework/slsa/issues/622, since I'm proposing dropping `builder.id` from the SLSA Provenance predicate. If we moved it to the Statement layer, this field would be more narrowly focused to hopefully avoid confusion. Maybe something like `onBehalfOf` to make it clear that it's only needed to differentiate who the attester is?

The alternative is to move it to DSSE, but that might be more work and with a different timeline.

**Comment by TomHennen** [comment]
We discussed inclusion of #136 at today's maintainers meeting.  While we understand the use case combining a lot of predicates into one statement can be an anti-pattern in that it prevents users from filtering out the predicate types they're not interested in if they want to only forward some of them (e.g. they're calling an API that has concerns about sending it huge amounts of data).

So we've decided it's too risky to include in v1, but are happy to discuss post-v1.

**Comment by TomHennen** [comment]
Tracking the attestor.id field in #137

**Comment by MarkLodato** [comment]
I think the URI should not have `.0` in it. According to our parsing rules, the `_type` ID should only contain a major version (which allows for breaking changes) but not a minor version (which cannot contain breaking changes).

**Comment by TomHennen** [comment]
Completed with @marcelamelara's tagging here: https://github.com/in-toto/attestation/releases/tag/v1.0
